name: Terraform Manual Plan (Self Hosted)

on:
  workflow_dispatch:   # 👈 Manual trigger only

jobs:
  terraform:
    name: Terraform Init and Plan
    runs-on: [self-hosted, label-1]   # 👈 Self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0                

